#!/bin/bash
# openoffice.org headless server script
#
### BEGIN INIT INFO
# chkconfig: 2345 80 30
# processname: openoffice
# Provides: openoffice headless
# Required-Start: $all
# Required-Stop: $all
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Start openoffice-headless at boot.
# Description: headless openoffice server script
### END INIT INFO

SOFFICE_PATH=/opt/libreoffice5.2/program/soffice
PID_SEARCH="pgrep -nf $SOFFICE_PATH"

set -e

case "$1" in
  start)
    if [ `$PID_SEARCH` ]; then
     echo "LibreOffice 5.2 headless server has already started."
    else
      echo "Starting LibreOffice 5.2 headless server"
      $SOFFICE_PATH --headless --nologo --nofirststartwizard --accept="socket,host=127.0.0.1,port=8100;urp" & > /dev/null 2>&1
    fi
  ;;

  stop)
    if [ `$PID_SEARCH` ]; then
      echo "Stopping LibreOffice 5.2 headless server."
      killall -9 soffice.bin
    else
      echo "Openoffice headless server is not running."
    fi
  ;;

  status)
    if [ `$PID_SEARCH` ]; then
      echo "LibreOffice 5.2 headless is running"
      exit 0
    else
      echo "LibreOffice 5.2 headless is not currently running, you can start it with $0 start"
      exit 1
    fi
  ;;

restart) $0 stop ; $0 start ;;
status) status ;;

*)
  echo "Usage: $0 {start|stop|restart|status}"
  exit 1
esac
exit 0