#!/bin/bash
#
# liferay-7.0-ga3 - This shell script takes care of starting and stopping Liferay-7.0-ga3
#
# chkconfig: - 80 20
#
### BEGIN INIT INFO
# Provides: liferay-7.0-ga3
# Required-Start: $network $syslog
# Required-Stop: $network $syslog
# Default-Start:
# Default-Stop:
# Short-Description: start and stop liferay-7.0-ga3
### END INIT INFO

SHUTDOWN_WAIT=45

tomcat_pid() {
    echo `ps aux | grep org.apache.catalina.startup.Bootstrap | grep -v grep | awk '{ print $2 }'`
}

start() {
    pid=$(tomcat_pid)
    if [ -n "$pid" ]
    then
        echo "Liferay-7.0-ga3 is already running (pid: $pid)"
    else
        # Start liferay-7.0-ga3
        echo "Starting Liferay-7.0-ga3"        
        /opt/liferay-ce-portal-7.0-ga3/tomcat-8.0.32/bin/startup.sh
        # Auto-start openoffice
        service openoffice start
    fi
    return 0
}

stop() {
    pid=$(tomcat_pid)
    if [ -n "$pid" ]
    then
        echo "Stopping Liferay-7.0-ga3"
        /opt/liferay-ce-portal-7.0-ga3/tomcat-8.0.32/bin/shutdown.sh

    let kwait=$SHUTDOWN_WAIT
    count=0
    count_by=5
    until [ `ps -p $pid | grep -c $pid` = '0' ] || [ $count -gt $kwait ]
    do
        echo "Waiting for processes to exit. Timeout before we kill the pid: ${count}/${kwait}"
        sleep $count_by
        let count=$count+$count_by;
    done

    if [ $count -gt $kwait ]; then
        echo "Killing processes which didn't stop after $SHUTDOWN_WAIT seconds"
        kill -9 $pid
    fi
    else
        echo "Liferay-7.0-ga3 is not running"
    fi

    return 0
}

case $1 in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        start
        ;;
    status)
       pid=$(tomcat_pid)
        if [ -n "$pid" ]
        then
           echo "Liferay-7.0-ga3 is running with pid: $pid"
        else
           echo "Liferay-7.0-ga3 is not running"
        fi
        ;;
esac

exit 0
